let autos = [
    {
        marca : 'Ford',
        modelo: 'Fiesta',
        color: 'Azul',
        anio: 2019,
        km: 200,
        precio: 150000,    
        cuotas: 12,
        patente: "APL123",
        vendido: true,
    },
    {
        marca : "Toyota",
        modelo: "Corolla",
        color: "Blanco",
        anio: 2019,
        km: 0,    
        precio: 100000,
        cuotas: 14,
        patente: 'JJK116',
        vendido: false,
    },
    {
        marca : 'Fiat',
        modelo: 'Cronos',
        color: 'Negro',
        anio: 2020,
        km: 300,
        precio: 200000,    
        cuotas: 10,
        patente: "JIS106",
        vendido: false,
    },
    {
        marca : 'Chevrolet',
        modelo: 'Sonic',
        color: 'gris',
        anio: 2021,
        km: 50,
        precio: 90000,    
        cuotas: 6,
        patente: "NBC911",
        vendido: true,
    },
];

module.exports = autos;